version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

  jobs:
    build:
      docker:
        - image: circleci/ruby:2.6.3-stretch-node
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
          RACK_ENV: test
          DATABASE_HOST: 127.0.0.1
        - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          executor: ruby/default
          parallelism: 1
          working_directory: ~/myapp
          steps:
            - checkout
            - run:
                name: sudo apt install -y postgresql-client || true
            - run: bundle clean --force
            - restore_cache:
              keys:
                - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
                - v1-gem-cache-{{ arch }}-{{ .Branch }}-
                - v1-gem-cache-{{ arch }}-
                  - run: sudo gem update --system
                    gem install bundler -v 2.1.4
                    bundle install --jobs=4 --retry=3 --path myapp/bundle
            - restore_cache:
              name: Restore Yarn Package Cache
              keys:
                - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
              name: Install Dependencies
              command: yarn install --immutable
            - save_cache:
              name: Save Yarn Package Cache
              key: yarn-packages-{{ checksum "yarn.lock" }}
              paths:
                - ~/.cache/yarn
